language: ruby

rvm:
 - 2.6.5

services:
 - postgresql

env:
 global:
  - MAGICK_CONFIGURE_PATH=$HOME/.config/ImageMagick

before_install:
 - cp config/database.yml.travis config/database.yml
 # Allow imagemagick to read PDF files
 - echo $MAGICK_CONFIGURE_PATH
 - mkdir $MAGICK_CONFIGURE_PATH
 - echo '<policymap>' > $MAGICK_CONFIGURE_PATH/policy.xml
 - echo '<policy domain="coder" rights="read | write" pattern="PDF" />' >> $MAGICK_CONFIGURE_PATH/policy.xml
 - echo '</policymap>' >> $MAGICK_CONFIGURE_PATH/policy.xml
 - sudo rm /etc/ImageMagick-6/policy.xml

before_script:
 - sudo apt-get update
 - sudo apt-get install -y ghostscript
 - psql -c 'create database travis_ci_test;' -U postgres
 - bin/rails db:migrate RAILS_ENV=test
